# Variable precedence(priority)
# 1. CLi
# 2. task level
# 3. role level
# 4. play level (a:100)
# 5. Inventory level

- name: Variables demo
  hosts: localhost
  connection: local
  vars:
    a: 100
  roles:
    - sample
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: a - {{ a }}
    - name: Print Variable task level
      vars:
        a: 200
      ansible.builtin.debug:
        msg: a - {{ a }}

- name: Variable demo1
  hosts: all
  tasks:
    - name: Variable From Inventory
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: Variable demo2
  hosts: all
  tasks:
    - name: Variable From Inventory vars
      ansible.builtin.debug:
        msg: URL2 - {{ URL2}}