## we are getting secret as a file in json format(:). but we the key value as need = format
- name: Vault demo
  hosts: localhost
  connection: local
  tasks:
    - name: Get Secret as file from vault
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-dev/data/frontend token={{ token }} url=http://vault-internal.maidevops.fun:8200') }}"

    - name: Copy using inline content
      ansible.builtin.copy:
        content: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-dev/data/frontend token={{ token }} url=http://vault-internal.maidevops.fun:8200') }}"
        dest: /tmp/content.json